/**
 * Compiles the agent definitions (.claude/context/agents/**) and transversal
 * prompts (.claude/context/prompts/*) into a generated TypeScript module so
 * both the Next.js app and Trigger.dev workers can bundle them without
 * filesystem access or custom loaders (Phase 2 decision, TDD U2).
 *
 * The .md files remain the ONLY source of truth. Regenerate with:
 *   npm run prompts:build
 *
 * The output is committed so prompt changes show up in code review diffs.
 */
import { createHash } from "node:crypto"
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(__dirname, "..")
const AGENTS_DIR = path.join(ROOT, ".claude", "context", "agents")
const PROMPTS_DIR = path.join(ROOT, ".claude", "context", "prompts")
const OUTPUT_FILE = path.join(ROOT, "lib", "orchestrator", "generated", "agent-prompts.ts")

function readAgentDefinitions(): Record<string, string> {
  const definitions: Record<string, string> = {}

  const teams = readdirSync(AGENTS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  for (const team of teams) {
    const files = readdirSync(path.join(AGENTS_DIR, team))
      .filter((file) => file.endsWith(".md"))
      .sort()
    for (const file of files) {
      const agentId = `${team}/${file.replace(/\.md$/, "")}`
      definitions[agentId] = readFileSync(path.join(AGENTS_DIR, team, file), "utf8")
    }
  }

  return definitions
}

function readTransversalPrompts(): Record<string, string> {
  const files: Record<string, string> = {
    responseRules: "response_rules.md",
    outputFormats: "output_formats.md",
    codingRules: "coding_rules.md",
  }
  const prompts: Record<string, string> = {}
  for (const [key, file] of Object.entries(files)) {
    prompts[key] = readFileSync(path.join(PROMPTS_DIR, file), "utf8")
  }
  return prompts
}

/** Builds the module source. Exported for the determinism test. */
export function generatePromptsModule(): string {
  const definitions = readAgentDefinitions()
  const transversal = readTransversalPrompts()

  const hash = createHash("sha256")
    .update(JSON.stringify({ definitions, transversal }))
    .digest("hex")
    .slice(0, 16)

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/build-agent-prompts.ts — DO NOT EDIT.",
    "// Source of truth: .claude/context/agents/** and .claude/context/prompts/*.",
    "// Regenerate with: npm run prompts:build",
    "",
    `export const PROMPTS_SOURCE_HASH = ${JSON.stringify(hash)}`,
    "",
    "export const AGENT_DEFINITIONS: Record<string, string> = {",
    ...Object.entries(definitions).map(
      ([id, content]) => `  ${JSON.stringify(id)}: ${JSON.stringify(content)},`
    ),
    "}",
    "",
    "export const TRANSVERSAL_PROMPTS = {",
    ...Object.entries(transversal).map(
      ([key, content]) => `  ${key}: ${JSON.stringify(content)},`
    ),
    "} as const",
    "",
  ]

  return lines.join("\n")
}

function main(): void {
  mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  writeFileSync(OUTPUT_FILE, generatePromptsModule(), "utf8")
  console.log(`Wrote ${path.relative(ROOT, OUTPUT_FILE)}`)
}

if (require.main === module) {
  main()
}
